sudo: false

language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION="~3.0"
    - SYMFONY_VERSION="~3.0" COMPOSER_FLAGS="--prefer-lowest"

matrix:
    fast_finish: true

    allow_failures:
        - php: hhvm

before_install:
    - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then phpenv config-rm xdebug.ini; fi;'
    - composer self-update
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script:
    - vendor/bin/phpunit --colors
